name: mailtm
description: mail.tm client

version: 0.0.1
homepage: https://orx.me
documentation: https://orx.me

environment:
   sdk: ">=2.12.0 <3.0.0"
   
dependencies: 
  json_annotation: ^4.4.0
  http: ^0.13.4


dev_dependencies:
  build_runner: ^2.0.0
  json_serializable: ^6.0.0
  test: ^1.20.1

